# Generated by Django 2.0.7 on 2018-08-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupride', '0003_auto_20180802_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='comments',
            field=models.ManyToManyField(blank=True, to='groupride.Comment'),
        ),
        migrations.AlterField(
            model_name='route',
            name='reviews',
            field=models.ManyToManyField(blank=True, to='groupride.Review'),
        ),
    ]
