# Generated by Django 2.0.7 on 2018-08-02 19:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupride', '0004_auto_20180802_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='confirmed_riders',
            field=models.ManyToManyField(related_name='confirmed_ride', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ride',
            name='invited_riders',
            field=models.ManyToManyField(related_name='invited_ride', to=settings.AUTH_USER_MODEL),
        ),
    ]
