# Generated by Django 2.0.7 on 2018-08-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupride', '0005_auto_20180802_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='ride_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
