# Generated by Django 2.0.7 on 2018-08-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupride', '0006_ride_ride_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='route_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
