# Generated by Django 2.0.7 on 2018-08-05 11:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('groupride', '0007_route_route_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='ride_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ride',
            name='ride_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='route',
            name='miles',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
    ]
