# Generated by Django 2.0.7 on 2018-08-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupride', '0008_auto_20180805_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='ride_time',
        ),
        migrations.AlterField(
            model_name='ride',
            name='ride_date',
            field=models.DateTimeField(),
        ),
    ]
