# Generated by Django 2.0.7 on 2018-08-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupride', '0009_auto_20180805_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='gpxfile',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
