# Generated by Django 2.0.7 on 2018-08-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupride', '0010_route_gpxfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='gpxfile',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
