# Generated by Django 2.0.7 on 2018-08-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupride', '0011_auto_20180806_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='gpxfile',
            field=models.FileField(blank=True, null=True, upload_to='groupride/uploads/'),
        ),
    ]
