# Generated by Django 2.0.7 on 2018-08-07 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupride', '0012_auto_20180806_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='gpxfile',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
