# Generated by Django 2.0.7 on 2018-08-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupride', '0014_auto_20180807_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(blank=True, choices=[('0', 'no rating given'), ('1', 'Entire route is not recommended and possibly dangerous.'), ('2', 'Sections of route are not recommended.'), ('3', 'Generally accepable. Nothing Special, but safe.'), ('4', 'Good. Recommended'), ('5', 'Outstanding!')], default=None, max_length=1),
        ),
    ]
